import { navigate, useNavigation } from '../navigation.ts';
import type { AnalysisResult } from '../../core/model/contracts.ts';
import { RegressionLab } from '../tools/RegressionLab.tsx';

type Tab='options'|'verification'|'regression';
export function PlanScreen({ result }: { result: AnalysisResult }) { const route=useNavigation(); const tab=(route.sub && ['options','verification','regression'].includes(route.sub) ? route.sub : 'options') as Tab; return <div className="space-y-5"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-[11px] uppercase tracking-[.18em] text-blue-300">Decision & Verification</div><h1 className="mt-1 text-xl font-semibold">方案与验证</h1><p className="mt-1 text-sm text-slate-400">保留原版本的候选方案比较、Verification Loop、设计回归入口，同时保证所有正式决策由 Pattern Measure 推导。</p></div><div className="flex gap-1">{([['options','方案比较'],['verification','验证闭环'],['regression','评审回归']] as const).map(([id,label])=><button key={id} onClick={()=>navigate({screen:'plan', sub:id})} className={`rounded-lg px-3 py-2 text-xs ${tab===id?'bg-blue-600/20 text-blue-300 border border-blue-500/30':'text-slate-400 hover:bg-slate-800'}`}>{label}</button>)}</div></div></section>
{tab==='options'&&<><section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="bg-slate-950/70 text-slate-500"><tr><th className="px-4 py-3">方案</th><th className="px-4 py-3">档位</th><th className="px-4 py-3">T</th><th className="px-4 py-3">S</th><th className="px-4 py-3">C</th><th className="px-4 py-3">Q</th><th className="px-4 py-3">L</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">VETO</th></tr></thead><tbody>{result.action.options.map((o)=><tr key={o.id} className="border-t border-slate-800"><td className="px-4 py-3 text-slate-200">{o.title}<div className="mt-1 text-[10px] text-slate-500">{o.requiresBoardRespin?'需改板':'不需改板'} · {o.cost} · {o.days}d</div></td><td className="px-4 py-3 text-slate-400">{o.tier}</td><td className="px-4 py-3 font-mono">{o.scores.T}</td><td className="px-4 py-3 font-mono">{o.scores.S}</td><td className="px-4 py-3 font-mono">{o.scores.C}</td><td className="px-4 py-3 font-mono">{o.scores.Q}</td><td className="px-4 py-3 font-mono">{o.scores.L}</td><td className="px-4 py-3 font-mono font-semibold">{o.scores.total}</td><td className="px-4 py-3">{o.veto.triggered?<span className="text-rose-300">YES · {o.veto.sourcePatternIds.join(', ')}</span>:<span className="text-emerald-300">NO</span>}</td></tr>)}</tbody></table></div></section><div className="grid gap-4 md:grid-cols-2"><Timeline title="T+24h 遏制" items={result.action.timeline.containment}/><Timeline title="永久纠正" items={result.action.timeline.permanent}/></div></>}
{tab==='verification'&&<section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-sm font-semibold">Verification Loop</h2><p className="mt-1 text-xs text-slate-500">风险 → 措施 → 验证 → 回灌实测 → 重新分析。</p><div className="mt-4 space-y-2">{result.action.options.map(o=><div key={o.id} className="rounded-xl border border-slate-800 bg-slate-950/50 p-3"><div className="text-xs font-medium text-slate-200">{o.title}</div><div className="mt-2 space-y-1">{o.verification.map(v=><div key={v} className="text-[11px] text-slate-400">□ {v}</div>)}</div></div>)}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-sm font-semibold">选择后的工程动作</h2><div className="mt-3 space-y-2">{(result.action.options.find(o=>o.id===result.action.recommended)?.verification || []).map(v=><div key={v} className="rounded-lg border border-slate-800 bg-slate-950/50 px-3 py-2 text-xs text-slate-300">{v}</div>)}{!result.action.recommended&&<div className="text-xs text-slate-500">当前没有推荐方案，通常意味着输入不足或没有触发 Pattern。</div>}</div></div></section>}
{tab==='regression'&&<RegressionLab/>}</div> }
function Timeline({title,items}:{title:string;items:AnalysisResult['action']['timeline']['containment']}){return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-sm font-semibold">{title}</h2><div className="mt-3 space-y-2">{items.length?items.map(i=><div key={i.optionId} className="rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-xs"><div className="text-slate-200">{i.title}</div><div className="mt-1 text-slate-500">{i.days}d · {i.requiresBoardRespin?'改板':'不改板'} · {i.vetoed?'当前仍有 Pattern VETO':'当前无 VETO'}</div></div>):<div className="text-sm text-slate-500">当前没有可进入该时间线的候选。</div>}</div></section>}
