import type { AnalysisResult } from '../../core/model/contracts.ts';

export function PlanScreen({ result }: { result: AnalysisResult }) {
  return <div className="space-y-5">
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h1 className="text-xl font-semibold">方案与验证</h1><p className="mt-1 text-sm text-slate-400">候选方案由当前触发 Pattern 的 Measure 派生。VETO 状态只能引用 Pattern。</p></section>
    <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="bg-slate-950/70 text-slate-500"><tr><th className="px-4 py-3">方案</th><th className="px-4 py-3">档位</th><th className="px-4 py-3">T</th><th className="px-4 py-3">S</th><th className="px-4 py-3">C</th><th className="px-4 py-3">Q</th><th className="px-4 py-3">L</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">VETO</th></tr></thead><tbody>{result.action.options.map((option) => <tr key={option.id} className="border-t border-slate-800"><td className="px-4 py-3 text-slate-200">{option.title}<div className="mt-1 text-[10px] text-slate-500">{option.requiresBoardRespin ? '需改板' : '不需改板'} · {option.cost} · {option.days}d</div></td><td className="px-4 py-3 text-slate-400">{option.tier}</td><td className="px-4 py-3 font-mono">{option.scores.T}</td><td className="px-4 py-3 font-mono">{option.scores.S}</td><td className="px-4 py-3 font-mono">{option.scores.C}</td><td className="px-4 py-3 font-mono">{option.scores.Q}</td><td className="px-4 py-3 font-mono">{option.scores.L}</td><td className="px-4 py-3 font-mono font-semibold">{option.scores.total}</td><td className="px-4 py-3">{option.veto.triggered ? <span className="text-rose-300">YES · {option.veto.sourcePatternIds.join(', ')}</span> : <span className="text-emerald-300">NO</span>}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-4 md:grid-cols-2">
      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-sm font-semibold">T+24h 遏制</h2><div className="mt-3 space-y-2">{result.action.timeline.containment.length ? result.action.timeline.containment.map((item) => <div key={item.optionId} className="rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-xs"><div className="text-slate-200">{item.title}</div><div className="mt-1 text-slate-500">{item.days}d · {item.vetoed ? '当前仍有 Pattern VETO' : '无当前 Pattern VETO'}</div></div>) : <div className="text-sm text-slate-500">当前没有可直接进入 T+24h 的非改板 Measure。</div>}</div></section>
      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-sm font-semibold">永久纠正</h2><div className="mt-3 space-y-2">{result.action.timeline.permanent.length ? result.action.timeline.permanent.map((item) => <div key={item.optionId} className="rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-xs"><div className="text-slate-200">{item.title}</div><div className="mt-1 text-slate-500">{item.requiresBoardRespin ? '改板路径' : '当前不改板'} · {item.vetoed ? 'Pattern VETO 仍需重新分析解除' : '无当前 VETO'}</div></div>) : <div className="text-sm text-slate-500">当前没有永久纠正候选。</div>}</div></section>
    </div>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-sm font-semibold">验证</h2><div className="mt-3 space-y-2">{result.action.options.flatMap((option) => option.verification.map((text) => <div key={`${option.id}:${text}`} className="rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-xs text-slate-300"><span className="mr-2 font-mono text-slate-600">{option.id}</span>{text}</div>))}</div></section>
  </div>;
}
